### ISSUE TITLE
When adding a ToDo item, a warning is issues

### ISSUE THREAD

**Issue by stevenornelas** [codefoundries/isomorphic-material-relay-starter-kit#10]
This is what I get when I add a ToDo item in the browser console:

```
Warning: RelayQueryWriter: Could not find a type name for record `client:client:-10969516171:VG9kbzo2`.
```

**Comment by thelordoftheboards** [comment]
I have the feeling this is related to [facebook relay issue 474](https://github.com/facebook/relay/issues/474). I am noticing other types of weird behavior related to the add mutation.

**Comment by babylon05** [comment]
This error no longer appears in v 0.6.1. btw kudos on the repo! One thing I noticed though is the live demo on Heroku is returning an Application Error.

**Comment by thelordoftheboards** [comment]
Thank you! I hope to eventually get it to the point where it has multiple examples with relay and material UI working together, to be used both as boilerplate and as examples. Gotta resolve the authentication issues next.

Something changed on Heroku in the last few days. Before they accepted lower case first letter `procfile`. When I updated with 0.6.1 I saw a warning that it should be capital letter, and the procfile was ignored. I renamed it to `Procfile` and updated, the warning is gone and when pushing it says build successful, but it still does not work. I will be looking into this next week. Thank you for alerting me.

**Comment by thelordoftheboards** [comment]
It turns out that the error appears only for authenticated users. This should be resolved once the authentication is complete, I will leave it open for now.

**Comment by thelordoftheboards** [comment]
Fixed with implementing completely isomorphic authentication. I tested with several use cases and none of them produced warnings or errors.

**Comment by thelordoftheboards** [comment]
Heroku is back in business. It was a packaging issue.
