### ISSUE TITLE
Build failed on Heroku

### ISSUE THREAD

**Issue by naptiv** [codefoundries/isomorphic-material-relay-starter-kit#100]
First, that's look like a dream starter kit, but something's wrong happen with da_cassandra/_client.js 

{ [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
/tmp/build_19441b60fb60a39fe07560eec2a68997/naptiv-stack-100557b/data/da_cassandra/_client.js:27
contactPoints: process.env.CASSANDRA_CONNECTION_POINTS.split(','),
TypeError: Cannot read property 'split' of undefined

**Comment by thelordoftheboards** [comment]
Thank you.
Can you check your heroku config? Mine is:

```
$heroku config
=== isomorphic-material-relay Config Vars
CASSANDRA_CONNECTION_POINTS: n/a
CASSANDRA_KEYSPACE:          n/a
JWT_SECRET: xxxxx......
```

Possibly the code that is checking for the CASSANDRA variables needs to be modified to ignore when they are undefined ...
If they are not set please try setting them using https://devcenter.heroku.com/articles/config-vars#setting-up-config-vars-for-a-deployed-application

If that works, I will modify the code to not require them.

**Comment by naptiv** [comment]
You're right
-----> Build succeeded! 
Awesome :+1:

**Comment by thelordoftheboards** [comment]
I added a check anyway, someone else might bump into the same.
