### ISSUE TITLE
Include example with Subscriptions

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/isomorphic-material-relay-starter-kit#107]
Investigate http://graphql.org/blog/subscriptions-in-graphql-and-relay/ and include an example with subscriptions, possibly for Translaticiarum since it has a fairly simple data model.

**Comment by thelordoftheboards** [comment]
Anyone know any good examples of using subscriptions?

**Comment by naptiv** [comment]
[Event-stream based GraphQL subscriptions](https://gist.github.com/OlegIlyenko/a5a9ab1b000ba0b5b1ad) may help

**Comment by thelordoftheboards** [comment]
After looking at these issues I am having the impression that subscriptions are not ready for prime time just yet:

https://github.com/webonyx/graphql-php/issues/9
https://github.com/graphql/graphql-js/issues/152
https://github.com/graphql-go/graphql/issues/49
https://github.com/graphql/graphql-js/issues/224
https://github.com/facebook/relay/issues/541
https://github.com/search?utf8=%E2%9C%93&q=Relay.Subscription

If there are no publicly available examples showing how to do subscriptions I will be closing this issue. Any ideas?

**Comment by thelordoftheboards** [comment]
I was not able to find any information about implementing subscriptions with the current version of Relay, I am closing the issue. Please re-open if more information is available.
