### ISSUE TITLE
UI responsiveness/performance

### ISSUE THREAD

**Issue by alexhawkins** [codefoundries/isomorphic-material-relay-starter-kit#113]
Have you noticed the slight lag when switching between different routes? 311ms is way too long. Ideally you want those numbers to < 0ms. example of a light speed site would be www.palantir.com. Granted, it's just static content but no reason we shouldn't be able to achieve that speed. React/Redux apps i've built in the past with material ui never took this long. So I'm wondering if this has to do with server-side rendering not being optimized for use with React ( in theory, I thought ssr would be faster because it has the best of client side and server side   http://tomdale.net/2015/02/youre-missing-the-point-of-server-side-rendered-javascript-apps/  ). I came across this slide share from React Conf 2015 that suggests server-side rendering performance is 'not great' http://www.slideshare.net/nickdreckshage/react-meetup. Have things changed since then?

Or is the lag coming from the graphQL server. If you look at your network requests in chrome dev tools, you'll see what i'm talking about. I've attached an image below. Let me know what you think. 

But once, again, this starter kit is awesome. I hope you keep developing it because I plan to use it in production. I'm trying to get your kit to work with micro services at the moment. Once you think your starter kit is ready, let me know. I'll help you make this thing go viral. I know exactly where to promote it.

<img width="317" alt="screenshot 2016-02-25 11 11 35" src="https://cloud.githubusercontent.com/assets/5912301/13331086/cc2be3c4-dbb0-11e5-9769-ffd5bb2089b8.png"> # #

**Comment by thelordoftheboards** [comment]
I will mark this as bug, since performance is important. I'll have to look in more detail at the sources you provided.

As for the readiness, I am planning for [version 1.0](https://github.com/codefoundries/isomorphic-material-relay-starter-kit/milestones/Version%201) to be that thing. Not that it would be perfect or anything, but at least the basics would be covered. Hit me up on https://twitter.com/Lordoftheboards I could use any kind of help :)

**Comment by alexhawkins** [comment]
Yeah, no problem. I'm building an app with your starter kit right now and will be implementing most of my requests. I'll make pull requests when I do and you can decide if you want to add. It's just going to take me a bit of time initially because I have a lot of other things going on.

I'm very new to graphQL and Relay so I'll likely have quite a few questions for you.

**Comment by thelordoftheboards** [comment]
Let me know when you get close to starting, let's coordinate and come up with agenda and come up with contrib rules so that we do not step on each other's toes.
Another thing that I have been thinking of is to provide some separation between baseline stuff (boilerplate) and examples.

**Comment by thelordoftheboards** [comment]
I renamed the issue since at this point it is unclear what is the culprit of the performance issues.

**Comment by thelordoftheboards** [comment]
@alexhawkins check out the performance now. There have been some changes to web pack and all, and I played with it and it seems fairly swift. What is your experience?

**Comment by thelordoftheboards** [comment]
Since both React 15 and Material-UI 0.15 have huge changes which significantly affect performance I am closing this. It can be reopened once those are implemented, with whatever the performance issues after the upgrades are.
