### ISSUE TITLE
Feature Request: Testing Suite ( Enzyme )

### ISSUE THREAD

**Issue by alexhawkins** [codefoundries/isomorphic-material-relay-starter-kit#114]
Would be nice to integrate component testing with Enzyme and chai-enzyme? https://github.com/airbnb/enzyme   https://github.com/producthunt/chai-enzyme

**Comment by thelordoftheboards** [comment]
Definitely a must. I was thinking of some mocha/chai tests, which would also help the automatic update of the dependencies in #24. Would you recommend a good tutorial on adding enzyme tests in a configuration like this, with webpack and all?

I am also thinking of trying to utilize the in-memory implementation of the data store to implement tests, might be useful ... just an idea.

**Comment by alexhawkins** [comment]
This is one of my favorite starter kits. https://github.com/davezuko/react-redux-starter-kit  It has my favorite testing suite config. Also uses CSS Modules and ESLint ( got to have eslint ). I also like how they use globals. Makes it easy to config different things for different environments.

Yeah, using in-memory for tests might be a good idea. Sort of like Mock Data, is that what you're thinking?

**Comment by alexhawkins** [comment]
Karma file https://github.com/davezuko/react-redux-starter-kit/blob/master/build/karma.conf.js
Also take a look at the webpack.config. It's nice how they've set it up so you can config things for PROD and DEV.  https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js

**Comment by thelordoftheboards** [comment]
Got it about the Karma.
Question about ESLint. Since Flowtype is already in the project, what benefit does ESLint bring to the table? What does ESLint do that Flowtype does not?

**Comment by alexhawkins** [comment]
Flowtype is great. I'm just familiar with Eslint. Stick with flow.

**Comment by thelordoftheboards** [comment]
If there are certain use cases that ESLint covers that Flow does not I would definitely add it. There is a babel plugin which allows them to coexist peacefully.

**Comment by thelordoftheboards** [comment]
Blog post about how it is done with React Native:
https://blog.formidable.com/unit-testing-react-native-with-mocha-and-enzyme-51518f13ba73#.oui9mnpbl

**Comment by thelordoftheboards** [comment]
Article about using Enzyme in AirBnB: https://medium.com/airbnb-engineering/enzyme-javascript-testing-utilities-for-react-a417e5e5090f#.19266h4a2

**Comment by thelordoftheboards** [comment]
Will not be done for this project. Tracking through https://github.com/codefoundries/UniversalRelayBoilerplate/issues/67
