### ISSUE TITLE
Feature Request: CSS Modules

### ISSUE THREAD

**Issue by alexhawkins** [codefoundries/isomorphic-material-relay-starter-kit#115]
CSS Modules would also be nice. 
This is a great article which has some of the best practices being currently used.
https://blog.risingstack.com/react-js-best-practices-for-2016/

**Comment by thelordoftheboards** [comment]
There is a css loader configured in webpack, and the main app imports https://github.com/codefoundries/isomorphic-material-relay-starter-kit/blob/master/webapp/styles/main.css . It is empty now but it does work, and at some point I even used it for the CSS of the main page but later inlined it to avoid reflows.
What else would you have in mind? The article, while great, is quite light on details about CSS.

**Comment by alexhawkins** [comment]
I guess your starter kit uses material ui which assumes you're not going to be making too many style changes any you do can be done inline via material ui style attribute. But a good example of css module use is this app....really nice for keeping all your css changes packed tightly with your components. https://github.com/ramsaylanier/WordPressExpress/tree/master/app/components  But only useful if you're writing a lot of custom css/scss.

**Comment by thelordoftheboards** [comment]
Indeed material-ui takes care of most of the boilerplate UI styles, however I am sure in the real world a lot of additional CSS would be required. I will keep this request open for now and see if the need materializes.

**Comment by thelordoftheboards** [comment]
I am closing this since regular CSS files can be included, and there is no obvious need for SASS or LESS at this point.
