### ISSUE TITLE
TypeError: onCacheMiss is not a function

### ISSUE THREAD

**Issue by babylon05** [codefoundries/isomorphic-material-relay-starter-kit#13]
I got this error since react-relay v0.6.1 was released about 4 hours ago. 0.6.0 works fine. 

RelayQueryField._RelayQuery2.default.Node.getConcreteQueryNode (/isomorphic-material-relay-starter-kit/node_modules/isomorphic-relay/lib/prepareData.js:55:12)
 at Object.<anonymous> (/isomorphic-material-relay-starter-kit/node_modules/react relay/lib/toGraphQL.js:99:19)

**Comment by thelordoftheboards** [comment]
I will look into it soon. Thank you for reporting.

**Comment by thelordoftheboards** [comment]
This might be an issue with isomorphic-relay and the changes in the new Relay.

https://github.com/denvned/isomorphic-relay/issues/11

**Comment by thelordoftheboards** [comment]
I committed an update where I fixed all the versions to a specific number, so that upgrades can not break them. One isomorphic-relay-router plays well with relay 0.6.1, I will look to update to the new versions.

**Comment by thelordoftheboards** [comment]
Release 0.6.1 has relay 0.6.1 and react router 2. That should work well.
