### ISSUE TITLE
task.ontimeout is not a function, followed by termination

### ISSUE THREAD

**Issue by terrisgit** [codefoundries/isomorphic-material-relay-starter-kit#19]
If I accidentally code a bug in, say, AppBar_Auth.jsx, I see the following in the console and then the 'npm start' command terminates.

 node_modules/seq-queue/lib/seq-queue.js:124 task.ontimeout();

 TypeError: task.ontimeout is not a function
    at [object Object]._onTimeout (node_modules/seq-queue/lib/seq-queue.js:124:9)
    at Timer.listOnTimeout (timers.js:92:15)

I don't see the original error on the console. There is no error reported by "npm install" either. This makes fixing the problem very difficult. Do I need to add an exception handler somewhere? That would have the benefit of my app not crashing.

**Comment by thelordoftheboards** [comment]
Do you mind sharing the code change you made? I would like to experiment with it and see what can be done.

**Comment by terrisgit** [comment]
Sure. I modified AppBar_Auth and intentionally broke the constructor

  constructor( props )
  {
    super( props );
    foo

I just pulled the latest. Now I get "Timeout for renderer" with no crash (see below). How do you troubleshoot/debug this yourself? Thank you for your help. The starter kit has already been a huge help!

--------------------------------------------------------------------------------
isomorphic-material-relay-starter-kit 0.6.5 running as production
Serving at undefined:4444
--------------------------------------------------------------------------------
Timeout for renderer

**Comment by thelordoftheboards** [comment]
Thank you. I will look into this.
As for the timeout, it is a sign that the server rendering did not finish within 2 seconds. Comes from the queue. Are you actually able to render the pages?
I am also noticing that `HOST` could not be read from the environment, judging by seeing
`Serving at `***`undefined`***`:4444`.

Do you have `HOST` in your `.env` file, or you set it with an environment variable? Can you check that?
Thank you for the compliment I am glad it helps. I would love IMRSK to get to a point where it can serve as more or less reliable starting point / examples and patterns repository.

**Comment by terrisgit** [comment]
I set the port number with an environment variable. I will create .env with your example. I am upgrading one of your older versions (1 month ago..) to your current version and having trouble, probably with the new react-router. I am diffing through your files to figure out what needs to be changed.

**Comment by thelordoftheboards** [comment]
Please double check the `renderOnServer.js`, the spelling here changed subtly:

```javascript
            const reactOutput = ReactDOMServer.renderToString(
                <IsomorphicRouter.RouterContext {...renderProps} />
            );
```

I would also recommend you to review https://github.com/codefoundries/isomorphic-material-relay-starter-kit/commit/6e47c7cbb65fa927862fcf687d4c1d90f5017617 . Hope this helps.

**Comment by terrisgit** [comment]
Thank you! That was very helpful.

**Comment by terrisgit** [comment]
Sorry to be annoying, but I just want to make sure that you know my question remains. How do you see server-side bugs? It appears that errors are not getting to the console or otherwise and all you see is a message about render timing out.

**Comment by thelordoftheboards** [comment]
I will keep it open. I will look into that soon.
