### ISSUE TITLE
Missing auth token on GraphiQL route in dev mode

### ISSUE THREAD

**Issue by eiktyrner** [codefoundries/isomorphic-material-relay-starter-kit#196]
I'm running this project using `npm run dev` so an auth token is shown at the bottom of the first page. Browing to `http://localhost:4444/graphql` gives an auth error since that token is not provided in the request.

Maybe that route shouldn't be protected in dev mode? 
Or the token should be automatically provided in the request.

Running on Arch Linux using the in-memory option if that matters.

**Comment by eiktyrner** [comment]
Didn't check #190

**Comment by thelordoftheboards** [comment]
Yeah, it's unfortunate. Ideally I would be able to enable using GraphiQL even with authentication but so far no luck.
