### ISSUE TITLE
Specify GraphQL URL

### ISSUE THREAD

**Issue by terrisgit** [codefoundries/isomorphic-material-relay-starter-kit#21]
I have .env that is setting HOST and PORT to values other than localhost/4444. However, when I hit the app's URL, the server-side outputs the following to the console. In my browser I get "Internal server error." I even tried changing the network layer myself in app.js and it had no effect. It's as if the network layer is getting set somewhere else.

Relay.injectNetworkLayer( new Relay.DefaultNetworkLayer( 'http://foo:4444/graphql', {
    credentials: 'same-origin',
  } )
);

renderOnServer: renderProps={"routes":[{"path":"/","queries":{}}],"params":{},"location":{"pathname":"/","search":"","hash":"","state":null,"action":"POP","key":"4mxl03","query":{},"$searchBase":{"search":"","searchBase":""}},"components":[null],"history":{"__v2_compatible__":true},"router":{"__v2_compatible__":true}}
request to http://localhost:4444/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4444
Error: request to http://localhost:4444/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4444
    at ClientRequest.<anonymous> (/home/ec2-user/context-hub-app/node_modules/node-fetch/index.js:117:11)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:262:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickDomainCallback (node.js:429:17)

**Comment by thelordoftheboards** [comment]
These are the two places:

https://github.com/codefoundries/isomorphic-material-relay-starter-kit/search?utf8=%E2%9C%93&q=DefaultNetworkLayer

One for server renderer, one on client.

**Comment by terrisgit** [comment]
Yes. I fixed this in app.js and renderOnServer.js

renderOnServer was hard-coding localhost. I don't know why, but that was a problem. I'm using EC2.

const GRAPHQL_URL = `http://${process.env.HOST}:${process.env.PORT}/graphql`;

**Comment by thelordoftheboards** [comment]
The assumption was they would live on the same server, but of course they can be separate. GraphQL would not care.

**Comment by terrisgit** [comment]
In my case, they both live on the server. app.js appears to be fine. Hard-coding localhost is a problem. No idea why, probably has to do with EC2's networking layer.

**Comment by thelordoftheboards** [comment]
Maybe it would make sense to make it into a setting, where HOST would not be the publicly accessible URL. Could be useful for all sorts of web farms reverse proxies scenarios. I'm gonna reopen this.

**Comment by terrisgit** [comment]
Yes, and would need control over https vs http

**Comment by thelordoftheboards** [comment]
I will definitely look into adding it soon. Even outside of the scope of this starter kit, it's always good to have a public URL handy for things like embedding links in emails, permalinks, call backs from 3rd party APIs, etc.

**Comment by thelordoftheboards** [comment]
https://github.com/codefoundries/isomorphic-material-relay-starter-kit/commit/1082a79f65bcec63311bc641597dc559ae438b73 should resolve this. If it does not, please reopen with description of how the new code is not working.
