### ISSUE TITLE
Creating schema.json

### ISSUE THREAD

**Issue by tur-ing** [codefoundries/isomorphic-material-relay-starter-kit#223]
Do I have to edit the graphql/schema.json manually for new entities or is there some trick to generate it automatically?

**Comment by tur-ing** [comment]
OK, sorry: npm run build-schema

**Comment by tur-ing** [comment]
It does not work: if I run 'npm run build-schema' I get the old schema again that's also included in this repo. Where do I have to define my new entities in order to generate the correct schema automatically?

**Comment by thelordoftheboards** [comment]
@tur-ing I do not know what changes are you making so I can not answer for sure. Assuming you are following the units structure, I would suggest to check the following places:

* Any fields to be added to the viewer are placed in [*_ViewerFields.js](https://github.com/codefoundries/isomorphic-material-relay-starter-kit/blob/master/units/starter-kit-example-ensayo/graphql/type/Ensayo_ViewerFields.js).
* Any mutations are placed in [_mutations.js](https://github.com/codefoundries/isomorphic-material-relay-starter-kit/blob/master/units/starter-kit-example-ensayo/graphql/mutation/_mutations.js).
* If you create a new unit, the respective viewer fields and mutations should be added to (_all)[https://github.com/codefoundries/isomorphic-material-relay-starter-kit/tree/master/units/_all]

Does this help? If you still do not have it working, and have your project publicly available, I can take a look.

**Comment by thelordoftheboards** [comment]
I also added more details to the file structure description:

https://github.com/codefoundries/isomorphic-material-relay-starter-kit/commit/dae33ebb40e718ae723aa57d0bdf8f6e2b960067
https://github.com/codefoundries/isomorphic-material-relay-starter-kit/commit/3347e0022e4182f8cf9feb114f15d47cd0d42077

Hope this helps.
