### ISSUE TITLE
Remove queue for rendering on the server-side?

### ISSUE THREAD

**Issue by joonhocho** [codefoundries/isomorphic-material-relay-starter-kit#225]
Two issues to make relay state contextual have been closed.
https://github.com/facebook/relay/issues/1025
https://github.com/facebook/relay/issues/558

Is it possible now to remove rendering queue on the server-side and take advantage of contextual state per request (session) basis?

**Comment by thelordoftheboards** [comment]
Implement after:

https://github.com/codefoundries/isomorphic-material-relay-starter-kit/issues/219

**Comment by joonhocho** [comment]
I guess it's done by the new repo?
https://github.com/codefoundries/UniversalRelayBoilerplate/blob/master/webapp/renderOnServer.js

**Comment by thelordoftheboards** [comment]
@joonhocho this is correct, the new version using relay 0.8 does not need the queue any more.
A problem which stems of how MUI is used is: https://github.com/codefoundries/UniversalRelayBoilerplate/issues/6
I am planning to resolve this by passing the agent to the component. But as far as Relay is concerned, it is all good I believe.

**Comment by thelordoftheboards** [comment]
Will not be done for this project, use https://github.com/codefoundries/UniversalRelayBoilerplate instead.
