### ISSUE TITLE
Automatic update of project dependencies

### ISSUE THREAD

**Issue by suribit** [codefoundries/isomorphic-material-relay-starter-kit#24]
Hi @thelordoftheboards .You have a cool project.
I want to offer you to use the http://greenkeeper.io/ - it periodically scans package.json and submits PRs with updated dependencies and it's free for open-source projects.
I think it will be useful for the project :wink:

**Comment by thelordoftheboards** [comment]
@wss-world This is an awesome idea. All the underlying packages are going through a rapid evolution and bringing new features all the time.

We would have to develop at least some basic tests to make sure that the new dependencies are not breaking everything.

It's been a pretty rough patch with the upgrades for babel,react, react-router/history, and relay router and the isomorphic version of them. I do not think semver versions where entirely correct, and things would not work, or require conflicting packages, etc. Now that we are on Babel 6, React Dom is split our, and react router is on version 2 I am hoping to hit a patch of stability.

How do you suggest we proceed with greenkeeper? What is best to use for testing?

**Comment by wss-world** [comment]
Yes you are right.
We need to develop basic tests, before the introduction of greenkeeper.

**Comment by thelordoftheboards** [comment]
The most important part would be to capture that the whole server route - server render - client route - client render path is reliable. In my experience that has been the most fragile part. That said, now that we are on react 0.14 and react-router 2, maybe it will just stay stable. Hard to predict those things.
I have not done testing in JavaScript before. What would you recommend?

**Comment by wss-world** [comment]
I think that we can do the following:
1. Create a test that will test the basic functionality. Frankly I had no experience with the tests in JavaScript.
2. We can leave it at that. With minor updates libraries (react-router v2.0.0-rc4 , react-router v2.0.0-rc5), we can not check the project, because that usually do not have these updates API changes.
I have not yet fully understood in the draft, maybe I'm wrong.

**Comment by babylon05** [comment]
Jest?

https://facebook.github.io/jest/

**Comment by thelordoftheboards** [comment]
It seems like facebook is using Jest for React internally:

https://facebook.github.io/jest/docs/tutorial-react.html

I will start learning it.

**Comment by babylon05** [comment]
Relay React testing strategies:

http://stackoverflow.com/questions/32760418/testing-strategy-on-relay-react

**Comment by thelordoftheboards** [comment]
By the way I am resorting to `npm shrinkwrap` as a solution to managing dependencies and getting repeatable results. Other than that it's simply impossible to get all components to agree on what version of React they want, or what version of Relay, or of some sub-component I've never heard of. Seems to fix the problems with Heroku deployment and sounds like the proper way to deploy in production environments.

**Comment by thelordoftheboards** [comment]
I've been using https://github.com/tjunnone/npm-check-updates lately and it seems to do good enough job, since testing is nowhere close to be implemented I will just close this issue. Once some tests exist, it can be re-opened.
