### ISSUE TITLE
Additional cassandra authentication schemes

### ISSUE THREAD

**Issue by terrisgit** [codefoundries/isomorphic-material-relay-starter-kit#31]
When connecting to Cassandra, support both passwordless and other authentication schemes such as username and password.

**Comment by thelordoftheboards** [comment]
Most probably putting a passport in front, and once auth is successful an JWT token is issued into auth_token and the rest proceeds as usual. Should be fairly straightforward to do.

**Comment by terrisgit** [comment]
I will submit a PR shortly.

**Comment by thelordoftheboards** [comment]
I am closing this and will track making the user and password mandatory through #34 .
