### ISSUE TITLE
CSRF attack prevention

### ISSUE THREAD

**Issue by terrisgit** [codefoundries/isomorphic-material-relay-starter-kit#37]
See also http://www.redotheweb.com/2015/11/09/api-security.html

Cross-site scripting (XSS) attacks are best thwarted with cookies.

CSRF attacks involve tricking users into clicking on URLs via third-party sites or email. These URLs cause data to be altered without the user's consent (e.g., mark all TODOs as complete). The only requirement is that the browser have a valid cookie to use the application.

The login module should produce two JWTs. One is stored in a cookie ("JWT cookie") and the other is stored in session state ("session JWT"). 

A Relay network layer should pass the session JWT via a header.

Relay queries and mutations should verify the JWT cookie. Relay mutations should also verify the session JWT.

**Comment by terrisgit** [comment]
Not sure if Relay or single page apps in general are somehow immune to CSRF.

**Comment by terrisgit** [comment]
See

**Comment by thelordoftheboards** [comment]
According to:

https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage/

SPA can indeed be vulnerable. The description of the solution you provided seems to fix the problem.

**Comment by thelordoftheboards** [comment]
The following article described CSRF in detail:

http://www.troyhunt.com/2010/11/owasp-top-10-for-net-developers-part-5.html
