### ISSUE TITLE
Warning about deprecated method when adding to do

### ISSUE THREAD

**Issue by stevenornelas** [codefoundries/isomorphic-material-relay-starter-kit#4]
I get the following message when adding a to do in the console:

*Warning: setValue() method is deprectated. Use the defaultValue property instead.
Or use this the TextField as a controlled component with the value property.*

**Comment by thelordoftheboards** [comment]
I will look into this, it seems that Material-UI have published instructions about the necessary modifications.

**Comment by thelordoftheboards** [comment]
I will treat this as a bug since the way material-ui should work, setValue( ) should not be used in this way.
