### ISSUE TITLE
Can't nam install 0.1.24

### ISSUE THREAD

**Issue by stevenornelas** [codefoundries/isomorphic-material-relay-starter-kit#5]
isomorphic-material-relay-starter-kit@0.1.24
├── UNMET PEER DEPENDENCY babel-relay-plugin@0.6.1
├─┬ cookie-parser@1.4.0
│ └── cookie@0.2.2
├── history@1.17.0
├── UNMET DEPENDENCY react@^0.14.4
└── react-dom@0.14.5

**Comment by thelordoftheboards** [comment]
I had to disallow upgrading of the versions, there is some confusion between react and react-dom 0.14.4 and 0.14.5.
Please try 0.1.26 and tell if it it works.

**Comment by stevenornelas** [comment]
0.1.26 installs fine.
