### ISSUE TITLE
Help with free hosting!

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/isomorphic-material-relay-starter-kit#54]
We are currently using Heroku for hosting a version of the app with the in-memory implementation. Heroku is awesome! However, the free service is being shut down when inactive, which leads to quite prolonged startup times, and does not offer Cassandra. If anyone can help with hosting on a server that has both Node and Cassandra
![image](https://cloud.githubusercontent.com/assets/7056535/12731248/d973c080-c8e4-11e5-839b-ddd96cbf7960.png)

**Comment by babylon05** [comment]
[Openshift ](https://www.openshift.com) might work. The free account comes with 3 gears (hosting for 3 web apss) that only idle after 24hrs. They also have [resource grants/credits](https://www.openshift.com/grants/) for open source projects.
Cassandra setup:
https://blog.openshift.com/cassandra-on-openshift/

**Comment by thelordoftheboards** [comment]
I could never get a proper node cartridge for Node there. I tried to install the Node app on there at no avail and at some point gave up. Have you installed Node 4+ on Open Shift? What cartridge did you use?

**Comment by babylon05** [comment]
I just setup an account & i'm running 4.2.3.

**Comment by thelordoftheboards** [comment]
Can you try to set up IMRSK? Here is what I did in my previous efforts (not successful):

https://github.com/codefoundries/isomorphic-material-relay-starter-kit/commit/7e2d10a58daf81a8d9761311262ba2fff757debd
https://github.com/codefoundries/isomorphic-material-relay-starter-kit/commit/c43e0fa11a02d8d948a3a8409fd3cb20a3b462eb
https://github.com/codefoundries/isomorphic-material-relay-starter-kit/commit/c1eb72effb8b1c696b97c4b49404c355f25974c7

I think `OPENSHIFT_INTERNAL_IP` and `OPENSHIFT_INTERNAL_PORT` can be somehow put in the .env, or provided through environment variables. However, `.openshift/action_hooks/build` and `.openshift/markers/NODEJS_VERSION` might still be necessary.

**Comment by thelordoftheboards** [comment]
Digital Ocean is also providing programs for hosting of open source projects I could send an application:

![image](https://cloud.githubusercontent.com/assets/7056535/12834201/a1b024f4-cb5a-11e5-810d-6727e8f22fd6.png)

@babylon05 if you are in the process of testing open shift, I will wait to hear the results, maybe we can just do it with open shift. I'd rather not bother digital ocean if there is an alternative solution. I do like the idea of using dokku though, something that digital ocean has perfected it seems.

**Comment by babylon05** [comment]
Yes I'll try setting up IMSRK, will keep you posted. I think there is team feature to add users to the account.

**Comment by babylon05** [comment]
So far so good:
-  Cassandra 3.0.2 is up on one gear (i'm able to connect to the CQL sh)  
-  Node 4.2.3 on another.

**Comment by thelordoftheboards** [comment]
Awesome stuff! I am excited!

**Comment by thelordoftheboards** [comment]
@babylon05 by the way please notice that as part of the post-install script, we have `config-da-memory`:

```json
    "postinstall": "npm run config-da-memory && npm run build-schema && npm run build-webpack",
```

I added this because it is very convenient for Heroku, but might not work with your setup depending on how you deploy. If necessary, I can look into modifying how that works. If change is indeed needed, please open a new issue to track it separately.

**Comment by babylon05** [comment]
I have setup imrsk w/ config-da-memory  @ http://086-imrsk.rhcloud.com/  running Node 4.2.3. Now onto connecting to Cassandra 3.02 (spinning on another gear). I'll submit PRs on the steps as soon as I'm done and transfer the account to you or if you prefer you can open another one.

**Comment by thelordoftheboards** [comment]
Awesome. I can see it and it is alive!

**Comment by babylon05** [comment]
[app-imrsk.rhcloud.com](url)  
So app 0.9.0 on one gear & DB  C* 3.3 on another.

**Comment by thelordoftheboards** [comment]
Awesome! I added it to the list, please feel free to PR any required setup files and installation instructions.

**Comment by babylon05** [comment]
I still have some changes to make to the deploy script hooks envs etc... so the link might not always work. Maybe we could add "under development" or something to that effect next to the link to avoid non issues.

**Comment by thelordoftheboards** [comment]
Done. Thank you!

**Comment by babylon05** [comment]
Now for the hacks ;)

Replaced bcrypt w/ [bcryptjs](https://www.npmjs.com/package/bcryptjs) (very easy to swap them) because of an outdated GCC on Osh.   They will hopefully update it soon seeing that there are a lot of Up votes for this. Let me know if this ok with you and I'll PR it. 

Moved FSEvents out of Shrinkwrap because I was getting -> ERR! code EBADPLATFORM
on Install.  Apparently [adding it to Op Deps in package.json](https://github.com/npm/npm/issues/2679#issuecomment-150084700) solves the multi platform problem.
Let me know if this ok also with you and I will test/ PR it.

Had to change localhost to HOST ENV in one or 2 places. (Will let you know exactly where)

Apart from these changes everything else is intact except for the ENV vars that i'm sourcing directly on Start from a file right now but using require( 'dotenv' ).load( ) should work fine.

**Comment by thelordoftheboards** [comment]
Great news!

bcryptjs PR is a OK - I would like to write an errata document that will describe certain ideosyncrasies like this, so that people cloning would be able to update to newer/faster, like in the case with bcrypt. I assume the APIs are compatible, right? If not we can write a super ultra-thin wrapper that would emulate the two or three methods of the bcrypt API we are using.

FSEvents - perfectly a OK. I assume I can still continue to use `npm shrinkwrap` in the future? I do it every time I add/update components - first delete the existing shrinkwrap file, then re-do it. If this mechanism will not work, please provide details on how to do it.

HOST ENV - let me know, I would ideally have it compatible with both Heroku and OSh.

If you can please also provide details about installing on OSh like installation steps, etc.

**Comment by babylon05** [comment]
bcryptjs - they're compatible so there is nothing change apart from the import statement to "from bcryptjs"

FSEvents: No problem for shrinkwrap

HOST ENV - go it.

I'll provide all the instructions, steps etc.. just wanted to clear this up first. After I'll transfer the account to you. I'll see if I can't just swap my email for yours.

I would not mind dockerizing IMRSK and see if we could get a sponsor host. I'll finish this first and maybe work on some of the other issues before.

**Comment by thelordoftheboards** [comment]
Thank you for your help! This is awesome.

As for Docker-izing - I am not very familiar. Would just making it compatible with Dokku be enough?

https://www.digitalocean.com/features/one-click-apps/dokku/
https://www.digitalocean.com/community/tutorials/how-to-use-the-dokku-one-click-digitalocean-image-to-run-a-node-js-app

I like the process of deploying through git and it seems dokku takes care of that, and, for all intents and purposes, acts like a one instance Heroku.

**Comment by babylon05** [comment]
Yes [Dokku](http://dokku.viewdocs.io/dokku/) is perfect. It's built on top of Docker. You can use the default Heroku buildpacks or Docker's native Dockerfile system to define a container. A bit new to me but I find the concept fascinating!

**Comment by thelordoftheboards** [comment]
Will not be done for this project. We are planning to make https://github.com/codefoundries/UniversalRelayBoilerplate use PM2.
