### ISSUE TITLE
Modernize handlers

### ISSUE THREAD

**Issue by terrisgit** [codefoundries/isomorphic-material-relay-starter-kit#55]
Speaking for myself, bind() doesn't make much sense to new JavaScript programmers. It is easy enough to read, but knowing when to use bind() is of those crufty bits of JavaScript folklore that in my opinion needs to be lost in history books. Arrow functions are the modern way to wire handlers. If you don't like using arrow functions for every handler reference, instead of writing a method, make it a property that holds an arrow function. If one purpose of this starter kit is to teach best practices, I think this is the way to introduce React to beginners. I am of course interested in your thoughts. Thank you.

Old:

  _handleAddToDo( )
  { ...
  }
...

  onEnterKeyDown={ this._handleAddToDo.bind( this ) }

New:

  _handleAddToDo = ( ) =>
  { ...
  };

...

  onEnterKeyDown={ this._handleAddToDo }

**Comment by thelordoftheboards** [comment]
I do not like the *look* of the arrow functions but I do like the brevity. For me the major selling point is that if the same handler is used twice, there is no need to bind the function twice. I will go ahead and update them. If you've done any of that already please PR.

**Comment by terrisgit** [comment]
Yes, if a handler is used only once, turning the method into a property is overkill.

**Comment by thelordoftheboards** [comment]
I do like

```javascript
_handleAddToDo = ( ) =>
{ ...
};
...
onEnterKeyDown={ this._handleAddToDo }
```

I do not like:

```javascript
_handleAddToDo( )
{ ...
}
...
onEnterKeyDown={ ( ) => this._handleAddToDo() }
```

because if the function has parameters it gets ugly:

```javascript
_handleAddToDo( p1, p2, p3 )
{ ...
}
...
onEnterKeyDown={ ( p1, p2, p3 ) => this._handleAddToDo( p1, p2, p3 ) }
```

However,

```javascript
_handleAddToDo = ( p1, p2, p3 ) =>
{ ...
};
...
onEnterKeyDown={ this._handleAddToDo }
```

is still elegant. So I will go with the latter. Time permitting I will be making that change, I doubt I will be able to make all at the same time.
