### ISSUE TITLE
Mark All To Dos is not working

### ISSUE THREAD

**Issue by stevenornelas** [codefoundries/isomorphic-material-relay-starter-kit#9]
When I use the checkbox the screen flickers, the unread indicator changes however then it goes back to how it was. I see this as a response from the GraphQL Server:

```javascript
{
  "data": {
    "markAllTodos": null
  },
  "errors": [
    {
      "message": "Cannot read property 'rootValue' of undefined",
      "locations": [
        {
          "line": 1,
          "column": 60
        }
      ]
    }
  ]
}
```

**Comment by wss-world** [comment]
Hi!
This switch does not operate again. Now error "message: "Cannot read property 'map' of undefined"".

I found the reason(https://github.com/codefoundries/isomorphic-material-relay-starter-kit/blob/master/data/da_memory/ToDo.js#L76). 
It makes sense?

**Comment by thelordoftheboards** [comment]
Something must have changed. I am currently in the midst of promisifying all ToDo code and preparing it for Cassandra, and will look into this also. I have broken some other ToDo stuff in the meantime.

**Comment by thelordoftheboards** [comment]
https://github.com/codefoundries/isomorphic-material-relay-starter-kit/commit/c2207312b0de915f33baa2eb2b231050118bbf5e should resolve the issue
